[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.eggs          # Exclude a few common directories in the
    | \.git           # root of the project.
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
force-exclude = '''
(
    i2c_lcd.py        # Exclude a few files in the
  | lcd_api.py        # root of the project.
)
'''
